### ISSUE TITLE
Servo Motor - PORTG0 (pin41) no PWM output

### ISSUE THREAD

**Issue by celoke** [AngelLM/Thor#80]
Hi,

Built the board, loaded the firmware on. All commands work except M3 to control the servo. Probed digital pin 41 no PWM output, is there something I'm missing? Please help

**Comment by celoke** [comment]
OK, got it to work, swapped to digital pin45 using OC5B instead

**Comment by AngelLM** [comment]
I'm sorry to be this late, but can you share how you solved it?
The original idea was to wire the pin that should go to the pin 41 to the pin 7 instead (as the 41 is digital and not PWM). This was because I made an mistake during the PCB design.
Did you wire the STool Signal to the Digital 45 pin? Is that pin PWM?

Thanks!
