### ISSUE TITLE
Suggested Material for Printing

### ISSUE THREAD

**Issue by sniperlucian** [AngelLM/Thor#93]
Could not find (e.g. FAQ) which material is suggest, respective which limitations are implied. (PET - flexible, PLA  - low temp. etc.)

Which experience exist?

**Comment by AngelLM** [comment]
Hi, that's a nice question.
I printed everinging except the motor holders and gears using PLA and I used ABS to print the small pieces in contact with the steppers such as gears and motor holders. 
Some people have printed it all using ABS (which I think is the best option if you are capable of printing it without problems).

In the first model of Thor there was not cooling system, the steppers tend to overheat, deforming the small PLA pieces in contact with the motors. That's why I used ABS in that pieces for the first version. After that I made a new design including fans for forced ventilation so the motors stay warm but do not deform the PLA pieces. Anyway I preferred to keep the holders and gears printed in ABS.

Hope it helps!
